### ISSUE TITLE
New customer + customer payments

### ISSUE THREAD

**Issue by theobouwman** [rikvdh/go-mollie#1]
Great work btw.

Is it true that creating a new issuer isn't covered yet?

Thanks in advance.

**Comment by rikvdh** [comment]
The Mollie API only has list issuers and get issuers.

https://www.mollie.com/en/docs/reference/issuers/list

https://www.mollie.com/en/docs/reference/issuers/get

**Comment by theobouwman** [comment]
I actually mean creating customers

**Comment by rikvdh** [comment]
That would be a valuable addition. Currently I've not implemented this. But then are Mandates and Subscriptions also valuable additions.

**Comment by theobouwman** [comment]
true, I'll make a pr later this day
